feat: database transactions
defi-wonderland/grants-stack-indexer-v2 pull request #48
Opened 2024-12-31 15:36 UTC by 0xnigir1

# 🤖 Linear

Closes GIT-217 GIT-214

## Description
As part of advanced recovery & error handling, we implement database transactions so we have a more granular control on DB operations, having the ability to rollback changes when -in a set of Changesets- one of the operation fails.

Note: the callback pattern isn't the best option but we're limited to it given the current Transaction API from Kysely

## Checklist before requesting a review

-   [ ] I have conducted a self-review of my code.
-   [ ] I have conducted a QA.
-   [ ] If it is a core feature, I have included comprehensive tests.

2024-12-31 17:52 UTC, jahabeebs reviewed
looks: good
comments: few

2024-12-31 17:52 UTC, jahabeebs commented on packages/data-flow/src/data-loader/dataLoader.ts
> +            this.logger.debug("Starting transaction...");
maybe would say "starting changeset transaction" or something since I imagine the repo may have other transactions happening

2024-12-31 17:52 UTC, jahabeebs commented on packages/data-flow/src/data-loader/dataLoader.ts
> +            this.logger.debug("Starting transaction...");
ideally somewhere there's a completed message too

2024-12-31 17:52 UTC, jahabeebs commented on packages/repository/src/repositories/kysely/application.repository.ts
> +    async insertApplication(application: NewApplication, tx?: Kysely<Database>): Promise<void> {
shouldn't this be called db not tx? elsewhere in the repo you define db: Kysely<Database>

2024-12-31 17:52 UTC, jahabeebs commented on packages/repository/src/repositories/kysely/application.repository.ts
> +        tx?: Kysely<Database>,
same comment as above

2024-12-31 17:52 UTC, jahabeebs commented on packages/repository/src/repositories/kysely/transactionManager.ts
> +    constructor(private readonly db: Kysely<Database>) {}
same thing, it's a db not a tx right 🤔

2024-12-31 17:52 UTC, jahabeebs commented on packages/repository/src/types/transaction.types.ts
> +// packages/repository/src/types/transaction.types.ts
delete comment

2024-12-31 17:52 UTC, jahabeebs commented on packages/repository/src/types/transaction.types.ts
> +export type KyselyTransaction = Kysely<Database>;
why are we using Kysely\<Database\> for the params that are "tx" rather than using KyselyTransaction? It might be nice to use KyselyTransaction for those if these really are txs so that it looks intentional rather than both txs and db params typed as Kysely\<Database\>

2024-12-31 19:46 UTC, 0xnigir1 commented on packages/repository/src/types/transaction.types.ts
> +export type KyselyTransaction = Kysely<Database>;
good catch ser, will update to the Transaction type from Kysely, this also addresses your prev comments and avoids the confussion

2024-12-31 19:53 UTC, 0xnigir1 commented on packages/repository/src/types/transaction.types.ts
> +export type KyselyTransaction = Kysely<Database>;
addressed: [6d5b44e](https://github.com/defi-wonderland/grants-stack-indexer-v2/pull/48/commits/6d5b44e3ee2078a627016f8739d1436064ba202a)

2024-12-31 19:53 UTC, 0xnigir1 commented on packages/data-flow/src/data-loader/dataLoader.ts
> +            this.logger.debug("Starting transaction...");
addressed: [6d5b44e](https://github.com/defi-wonderland/grants-stack-indexer-v2/pull/48/commits/6d5b44e3ee2078a627016f8739d1436064ba202a)

2024-12-31 20:01 UTC, jahabeebs approved these changes
Seems tests are failing

2025-01-01 04:00 UTC, jahabeebs requested changes
After pipeline fix will approve 👌

2025-01-02 05:26 UTC, jahabeebs approved these changes

2025-01-02 22:00 UTC, 0xkenj1 reviewed
gj ser, some minor commnets

2025-01-02 22:00 UTC, 0xkenj1 commented on packages/data-flow/test/data-loader/dataLoader.spec.ts
is there a way to test reveted records on the database, like an in memory pg ?

2025-01-02 22:00 UTC, 0xkenj1 commented on packages/data-flow/test/data-loader/dataLoader.spec.ts
Maybe i am not sure how txs work.  Changes are applied one by one and if some fails it reverts the applied ? or it applies all the changes at the same time and if something fails nothing is applied ?

2025-01-02 22:00 UTC, 0xkenj1 commented on packages/data-flow/test/data-loader/handlers/donation.handlers.spec.ts
should we add a todo or linear task for testing invalid inputs to handlers ?

2025-01-03 12:39 UTC, 0xnigir1 commented on packages/data-flow/test/data-loader/dataLoader.spec.ts
txs are _all or nothing_, so all changes are applied or neither of them. regarding tests, yeah that would be nice but these are e2e tests not unit so i was planning on attacking them on the e2e milestone, we don't want to test Kysely library itself but rather that the whole system works as expected

2025-01-03 12:43 UTC, 0xnigir1 commented on packages/data-flow/test/data-loader/handlers/donation.handlers.spec.ts
add it to Enhancements milestone 🫡

2025-01-03 12:54 UTC, 0xyaco approved these changes

2025-01-03 13:04 UTC, merged